### ISSUE TITLE
requirements.txt missing in package on PyPi

### ISSUE THREAD

**Issue by jmelett** [Usama0121/ariadne-jwt#11]
Hi there,

Thanks for creating this package. I noticed that the package on PyPi misses the requirments.txt, which causes the install to fail. Installing it via pip from GitHub works though.

Cheers

`#8 5.180       ERROR: Command errored out with exit status 1:
#8 5.180        command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-c833913s/ariadne-jwt/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-c833913s/ariadne-jwt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q69q_jk3
#8 5.180            cwd: /tmp/pip-resolver-c833913s/ariadne-jwt/
#8 5.180       Complete output (5 lines):
#8 5.180       Traceback (most recent call last):
#8 5.180         File "<string>", line 1, in <module>
#8 5.180         File "/tmp/pip-resolver-c833913s/ariadne-jwt/setup.py", line 21, in <module>
#8 5.180           with open('requirements.txt', 'r') as fin:
#8 5.180       FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by Usama0121** [comment]
I did not encounter this issue.
the following command worked fine
`pip install ariadne-jwt`
